apiVersion: v1
kind: ConfigMap
metadata:
  name: my-service-config
  namespace: fido
data:
  ENV: "production"
  ARGOCD_SERVER: "localhost"
  ARGOCD_PORT: "ARGOCD_PORT"
  ARGOCD_URL_PROD: "https://argocd-server.argocd.svc.cluster.local:443"
  ARGOCD_URL_LOCAL: "localhost:4040"
  ARGOCD_URL: "localhost:4040"
  ARGOCD_URL: "localhost:4040"
  TOKEN_CACHE_TTL: "600"
